
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt \
             && pip install --no-cache-dir -r requirements-dev.txt \
             && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    env_file:
      - .env
