# fly.toml app configuration file generated for your face-swap app

app = "ai-convert"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/"

[env]
  DJANGO_SETTINGS_MODULE = "django_project.settings.prod"
  PORT = "8000"

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"

[deploy]
  release_command = "python manage.py migrate"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1