# Generated by Django 5.1.6 on 2025-06-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fused/'),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='output_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
