# Generated by Django 5.1.6 on 2025-06-14 19:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0002_generatedimage_output_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='output_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/fused/'),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='selfie',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/selfies/'),
        ),
    ]
