# Generated by Django 5.1.6 on 2025-07-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0005_usagesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedimage',
            options={'ordering': ['-created_at']},
        ),
    ]
