name: Django CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: art_moving
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/art_moving
        DJANGO_SETTINGS_MODULE: django_project.settings.test
        PYTHONUNBUFFERED: 1
        STRIPE_PUBLISHABLE_KEY: dummy-key-for-tests
        STRIPE_SECRET_KEY: dummy-secret-for-tests
        STRIPE_WEBHOOK_SECRET: dummy-webhook-for-tests

        RECAPTCHA_PUBLIC_KEY: test
        RECAPTCHA_PRIVATE_KEY: test

        EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
        EMAIL_HOST: smtp.test.com
        EMAIL_PORT: 587
        EMAIL_USE_TLS: true
        EMAIL_HOST_USER: test@test.com
        EMAIL_HOST_PASSWORD: testpassword
        DEFAULT_FROM_EMAIL: noreply@test.com

        GOOGLE_CLIENT_ID: test-google-client-id
        GOOGLE_CLIENT_SECRET: test-google-client-secret

        CLOUDINARY_CLOUD_NAME: dummy_cloud
        CLOUDINARY_API_KEY: dummy_key
        CLOUDINARY_API_SECRET: dummy_secret


    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: pytest
